In [1]:
import matplotlib.pyplot as plt
from matplotlib.widgets import Cursor
import seaborn as sns
import numpy as np
import pandas as pd
import math
from datetime import datetime
import glob, os
from scipy.optimize import curve_fit


plt.rcParams['figure.dpi'] = 150
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['figure.max_open_warning']=False
plt.style.use('seaborn-white')


data_DIR = "./data/"
data_bio_DIR = "./data_biologic/"
fig_DIR = "./figs/"
%matplotlib widget

In [2]:
def load_data(test_no):
    test = "test"
    ldc_files=[]
    for file in os.listdir(data_DIR):
        if test in file and ".csv" in file:
            # print(file)
            ldc_files.append(file)
    ldc_file = ldc_files[test_no-1]

In [3]:
test_no =2
test = "test_data_"
# ldc_files=[]
# for file in os.listdir(data_bio_DIR):
#     if test in file and ".mpt" in file:
#         print(file)
#         ldc_files.append(file)
bio_file = test+str(test_no)+'.mpt'
bio_file

'test_data_2.mpt'

In [7]:
num_header_lines = 93
# dldc=pd.read_csv(data_bio_DIR+bio_file,on_bad_lines='skip')
df = pd.read_csv(data_bio_DIR+bio_file, header=num_header_lines, sep='\t', encoding='ISO-8859-1')
df
# df.columns

,mode,ox/red,error,control changes,Ns changes,counter inc.,Ns,I Range,time/s,control/mA,...,Capacitance discharge/ÂµF,x,Q discharge/mA.h,Q charge/mA.h,Capacity/mA.h,Efficiency/%,cycle number,P/W,R/Ohm,Unnamed: 30
0,3,0,0,0,0,0,0,115,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,NaN
1,3,0,0,0,0,0,0,115,10.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,NaN
2,3,0,0,0,0,0,0,115,20.000001,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,NaN
3,3,0,0,0,0,0,0,115,30.000001,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,NaN
4,3,0,0,0,0,0,0,115,40.000002,0.0,...,0.0,0.000000,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35144,3,0,0,0,0,1,5,115,350690.531317,0.0,...,0.0,-5.343536,3783.301123,0.0,3783.301123,0.00000,10.0,0.0,0.0,NaN
35145,3,0,0,0,0,1,5,115,350700.531318,0.0,...,0.0,-5.343536,3783.301123,0.0,3783.301123,0.00000,10.0,0.0,0.0,NaN
35146,3,0,0,0,0,1,5,115,350710.531319,0.0,...,0.0,-5.343536,3783.301123,0.0,3783.301123,0.00000,10.0,0.0,0.0,NaN
35147,3,0,0,0,0,1,5,115,350720.467320,0.0,...,0.0,-5.343536,3783.301123,0.0,3783.301123,0.00000,10.0,0.0,0.0,NaN
35148,3,0,0,0,0,1,5,115,350720.525320,0.0,...,0.0,-5.343536,3783.301123,0.0,3783.301123,100.01607,10.0,0.0,0.0,NaN